[tool.poetry]
name = "academic-chatgpt"
version = "0.2.0"
description = ""
authors = ["Yangyang Li <yangyang.li@northwestern.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
gradio = "^3.23.0"
loguru = "^0.6.0"
requests = "^2.28.2"
mdtex2html = "^1.2.0"
pydantic = "^1.10.7"
toml = "^0.10.2"
latex2mathml = "^3.75.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.1"
ruff = "^0.0.259"
pip-tools = "^6.12.3"


[tool.poetry.scripts]
chataca = "academic_chatgpt.__main__:cli"


[tool.ruff]
line-length = 120
extend-ignore = ["E501"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
